version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: leyline
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: restapi
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
